### ISSUE TITLE
Using `brms` functions on `flocker_fit` objects

### ISSUE THREAD

**Issue by abfleishman** [jsocolar/flocker#46] opened 2021-11-10 01:37 UTC
I was hoping to use functions from `brms` to work with the `flocker_fit` objects.  Specifically, I am interested in the `brms::conditional_effect` and some of the `brms::pp_check`s.
It looks like they do not run, see example:

```
library(brms)
library(flocker)
ex_data <- example_flocker_data()

flocker_data <- make_flocker_data(obs = ex_data$obs, 
                                  unit_covs = ex_data$unit_covs, 
                                  event_covs = ex_data$event_covs)

m<-flock(f_occ = ~ uc1, 
      f_det = ~ 1, 
      flocker_data = flocker_data,
      backend = "cmdstanr")

conditional_effects(m,effects = "uc1")
```
> Error in get(out, family$env) : 
  > object 'posterior_epred_occupancy_V' not found
```

pp_check(m)
```
> Using 10 posterior draws for ppc type 'dens_overlay' by default.
> Error in get(out, family$env) : 
>   object 'posterior_predict_occupancy_V' not found

**Comment by jsocolar** [comment] 2021-12-10 18:51
Thanks for opening this! I think that we ultimately want to do something a bit more bespoke here than just providing the necessary functions to make `brms::pp_check` work out-of-the-box.  The issue is that in occupancy models the likelihood doesn't factorize down to the visit level, meaning that there's a substantial loss of information if we report PPCs based on the visit-level outcome.  I think we ultimately want to develop our own PPC functions that apply some of the common PPCs used in occupancy modeling.

Likewise, we need to distinguish conditional effects in the occupancy sub-model from conditional effects in the detection sub-model.  We probably don't want to directly provide the conditional effects of *either* set of terms on the observed response, but rather provide those effects for the detection sub-model conditional on occupancy, and for the occupancy sub-model we want the effects on the latent occuapncy state and not the observed data. 

I'll probably have time in a week or two to try to implement some of this.

**Comment by abfleishman** [comment] 2021-12-10 19:13
@jsocolar that makes sense.  I am a bit of a novice when it comes to working with these results objects and that is why I was hoping to go for the functions from `brms`.  I wish I could contribute in a meaningful way here but I cannot.  I look forward to any updates you implement!  Thanks!

**Comment by jsocolar** [comment] 2021-12-11 03:04
Opening these issues is a very meaningful contribution!

**Comment by jsocolar** [comment] 2023-04-13 04:04
Hi @abfleishman , sorry this is taking so long to get done.  Life gets in the way...  

There are separate issues open for both posterior predictive checks and conditional effects, so I'm going to close this one now.  If you have specific near-term needs for this functionality, let me know and I'll see if I can prioritize!

**Closed** 2023-04-13 04:04 UTC
